
export const PRODUCTS = {
  "CREDITO_PESSOAL": 1,
  "PORTABILIDADE_CREDITO": 2,
  "FINANCIAMENTO_IMOBILIARIO": 3,
  "CARTAO_BENEFICIOS": 4,
  "CREDITO_VEICULO": 5,
  "EMPRESTIMO_CONSIGNADO": 6,
  "PORTABILIDADE_EMPRESTIMO": 7,
  "CONSORCIO": 8,
  "SAQUE_ANIVERSARIO": 9,
  "GARANTIA_IMOVEL": 10,
  "CREDITO_IMOBILIARIO": 11
}
